version: '3.8'

services:
  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://backend:8000
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - FASTAPI_ENV=production
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge